package uz.solarnature.solarnaturebot.domain.enumeration;

public enum UserState {

    NONE,
    MENU,
    NOT_STARTED,
    CHOOSE_LANGUAGE,
    PHONE,
    NAME,
    EMAIL,
    ADDRESS,
    COMPANY_NAME,
    COMPANY_TIN,
    DOCUMENT_TYPE,
    ACCOUNT_TYPE,
    OTHERS, VISIT_DATE, STATION_TYPE, STATION_TYPE_OTHER, BUILDING_TYPE, SES_POWER, BUILDING_TYPE_OTHER, PLAN, PAYMENT_FORM, TOOL_TYPE_PANEL, TOOL_TYPE_INVERTER, CONTACT_TIME, COMMERCIAL_OFFER, TOOL_TYPE_PANEL_OTHER, TOOL_TYPE_INVERTER_OTHER, FILLING_TYPE,

}
