spring:
  application:
    name: solar-nature-bot

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/solar_nature
    username: postgres
    password: 123
  messages:
    basename: i18n/messages

application:
  bot:
    token: 7076705214:AAGac1F_UM7wbCDiFZ9x89Lfk44ES_ivY08
    username: solar_nature_questionaire_bot
  file-storage:
    root-path: /Users/vcuv/PROJECTS/filestorage/solar_nature_bot